const { MongoMemoryServer } = await import('mongodb-memory-server');
const mongoose = (await import('mongoose')).default;
let mongod;
try { mongod = await MongoMemoryServer.create({ binary: { version: '7.0.14' } }); } catch (e) { console.log('SKIP no binary:', e.message); process.exit(0); }
await mongoose.connect(mongod.getUri('heal_test2'));
const request = (await import('supertest')).default;
const { default: app } = await import('./src/app.js');
const agent = request.agent(app);
const reg = await agent.post('/api/auth/register').send({ name: 'Heal User', email: 'heal@test.app', password: 'StrongPass1' });
const Trip = (await import('./src/models/Trip.js')).default;
const Itinerary = (await import('./src/models/Itinerary.js')).default;
const user = await (await import('./src/models/User.js')).default.findOne({ email: 'heal@test.app' });
const trip = await Trip.create({ user: user._id, title: 'T', origin: '', destination: 'Goa', startDate: new Date('2025-06-01'), endDate: new Date('2025-06-03'), travelers: { adults: 2, children: 0 }, budget: { total: 50000, currency: 'INR' } });
const itin = await Itinerary.create({ trip: trip._id, user: user._id, currency: 'INR', totalEstimatedCost: 0, days: [{ dayNumber: 1, date: new Date('2025-06-01'), activities: [{ time: '09:00', slot: 'morning', title: 'Fort Aguada', place: 'Fort Aguada', category: 'attraction', cost: { amount: 0, currency: 'INR', isEstimate: true }, dataStatus: 'estimate' }] }] });
await Itinerary.updateOne({ _id: itin._id }, { $set: { validation: { passed: false, issues: ['Day 1: overlap'], warnings: [], validatedAt: new Date() } } });
const healed = await agent.get(`/api/trips/${trip._id}/itinerary`);
console.log('status:', healed.status);
console.log('validation:', JSON.stringify(healed.body.data?.itinerary?.validation));
console.log('issues is array:', Array.isArray(healed.body.data?.itinerary?.validation?.issues));
await mongoose.disconnect();
